# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Subset Expression Plugin CI tests

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
          qgis_repo: ['ubuntu-ltr', 'ubuntu']

    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install flake8 pytest-xdist mock
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
        sudo wget -qO - https://qgis.org/downloads/qgis-2022.gpg.key | sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/qgis-archive.gpg --import
        sudo chmod a+r /etc/apt/trusted.gpg.d/qgis-archive.gpg
        sudo sh -c 'echo "deb [arch=amd64] https://qgis.org/${{ matrix.qgis_repo }} noble main" >> /etc/apt/sources.list'
        sudo apt update
        sudo apt install qgis xvfb
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        xvfb-run pytest -v

  release:
    runs-on: ubuntu-24.04
    env:
      QGIS_TOKEN: ${{ secrets.QGIS_ORG_PLUGIN_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_VERSION: ${{ github.event.release.tag_name }}
    if: ${{ github.event_name == 'release' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install qtbase5-dev qttools5-dev-tools
          sudo pip install qgis-plugin-ci
      - name: Release
        run: |
          qgis-plugin-ci release ${RELEASE_VERSION} --github-token ${GITHUB_TOKEN} --qgis-token ${QGIS_TOKEN}